# .github/workflows/static.yml
name: Deploy WordWarp to GitHub Pages

on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with your dependencies

      - name: Build static assets
        run: |
          # Add commands to build your static assets (e.g., CSS, JS, HTML)
          # For example, you might use a build tool like Flask or a static site generator

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/your/static/assets  # Update with the path to your built static assets
          publish_branch: gh-pages  # Update if you want to deploy to a different branch
         
